lint:
  container_configs: false
  files_unchanged:
    - .github/PULL_REQUEST_TEMPLATE.md
  merge_markers:
    - modules/nf-core/bowtie2/align/tests/main.nf.test.snap
  nextflow_config:
    - config_defaults:
        - params.markdown_path
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Katalin Ferenc, Sviatoslav Sidorov, Damir Baranasic
  description: CAGE-sequencing analysis pipeline with trimming, alignment and counting
    of CAGE tags.
  force: false
  is_nfcore: true
  name: cageseq
  org: nf-core
  outdir: .
  version: 2.0.0dev
