name: "cager_processing"
description: Tagcluster and consensus cluster calling
keywords:
  - CAGE
  - tagcluster
  - consensus cluster
tools:
  - "optparse":
      description: "A command-line option parser for R"
      homepage: "https://CRAN.R-project.org/package=optparse"
      documentation: "https://cran.r-project.org/web/packages/optparse/refman/optparse.html"
      doi: "10.32614/CRAN.package.optparse"
      licence: ["GPL-2 | GPL-3"]
      identifier: optparse
  - "rlang":
      description: "Functions for Base Types and Core R and 'Tidyverse' Features"
      homepage: "https://cran.r-project.org/web/packages/rlang/index.html"
      documentation: "https://rlang.r-lib.org/"
      doi: "10.32614/CRAN.package.rlang"
      licence: ["MIT + file"]
      identifier: rlang
  - "CAGEr":
      description: "Analysis of CAGE (Cap Analysis of Gene Expression) sequencing data for precise mapping of transcription start sites and promoterome mining"
      homepage: "https://www.bioconductor.org/packages/release/bioc/html/CAGEr.html"
      documentation: "https://www.bioconductor.org/packages/release/bioc/vignettes/CAGEr/inst/doc/CAGEexp.html"
      tool_dev_url: "https://github.com/charles-plessy/CAGEr"
      doi: "10.18129/B9.bioc.CAGEr"
      licence: ["GPL-3"]
      identifier: cager
  - "GenomicFeatures":
      description: "Query the gene models of a given organism/assembly"
      homepage: "https://bioconductor.org/packages/devel/bioc/html/GenomicFeatures.html"
      documentation: "https://bioconductor.org/packages/devel/bioc/vignettes/GenomicFeatures/inst/doc/GenomicFeatures.html"
      tool_dev_url: "https://github.com/Bioconductor/GenomicFeatures"
      doi: "10.1371/journal.pcbi.1003118"
      licence: ["Artistic-2.0"]
      identifier: genomicfeatures
  - "dplyr":
      description: "A grammar of data manipulation"
      homepage: "https://cloud.r-project.org/web/packages/dplyr/index.html"
      documentation: "https://dplyr.tidyverse.org/"
      tool_dev_url: "https://github.com/tidyverse/dplyr/"
      doi: "10.32614/CRAN.package.dplyr"
      licence: ["MIT + file"]
      identifier: dplyr
  - "purrr":
      description: "Functional Programming Tools"
      homepage: "https://cran.r-project.org/web/packages/purrr/index.html"
      documentation: "https://purrr.tidyverse.org/"
      tool_dev_url: "https://github.com/tidyverse/purrr/"
      doi: "10.32614/CRAN.package.purrr"
      licence: ["MIT + file"]
      identifier: purrr
  - "magrittr":
      description: "A Forward-Pipe Operator for R"
      homepage: "https://cran.r-project.org/web/packages/magrittr/index.html"
      documentation: "https://magrittr.tidyverse.org/"
      tool_dev_url: "https://github.com/tidyverse/magrittr/"
      doi: "10.32614/CRAN.package.magrittr"
      licence: ["MIT + file"]
      identifier: magrittr
  - "stringr":
      description: "Simple, Consistent Wrappers for Common String Operations"
      homepage: "https://cran.r-project.org/web/packages/stringr/index.html"
      documentation: "https://stringr.tidyverse.org/"
      tool_dev_url: "https://github.com/tidyverse/stringr/"
      doi: "10.32614/CRAN.package.stringr"
      licence: ["MIT + file"]
      identifier: stringr
  - "tidyr":
      description: "Tidy Messy Data"
      homepage: "https://cran.r-project.org/web/packages/tidyr/index.html"
      documentation: "https://tidyr.tidyverse.org/"
      tool_dev_url: "https://github.com/tidyverse/tidyr/"
      doi: "10.32614/CRAN.package.tidyr"
      licence: ["MIT + file"]
      identifier: tidyr
  - "tibble":
      description: "Simple Data Frames"
      homepage: "https://cran.r-project.org/web/packages/tibble/index.html"
      documentation: "https://tibble.tidyverse.org/"
      tool_dev_url: "https://github.com/tidyverse/tibble/"
      doi: "10.32614/CRAN.package.tibble"
      licence: ["MIT + file"]
      identifier: tibble
  - "data.table":
      description: "Extension of 'data.frame'"
      homepage: "https://cran.r-project.org/web/packages/data.table/index.html"
      documentation: "https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html"
      tool_dev_url: "https://github.com/Rdatatable/data.table"
      doi: "10.32614/CRAN.package.data.table"
      licence: ["MPL-2.0 + file"]
      identifier: data.table
  - "rtracklayer":
      description: "R interface to genome annotation files and the UCSC genome browser"
      homepage: "https://bioconductor.org/packages/devel/bioc/html/rtracklayer.html"
      documentation: "https://bioconductor.org/packages/devel/bioc/vignettes/rtracklayer/inst/doc/rtracklayer.pdf"
      tool_dev_url: "https://github.com/lawremi/rtracklayer"
      doi: "10.1093/bioinformatics/btp328"
      licence: ["Artistic-2.0 + file"]
      identifier: rtracklayer
input:
  - cager_obj:
      type: file
      description: |
        Path to a CAGEr object file containing annotated CAGE data.
        The CAGEr object should be saved in RDS format.
      pattern: "*{.rds}"
  - bsgenome_file:
      type: file
      description: The forged BSgenome package in tar.gz format.
      pattern: "BSgenome.*.tar.gz"
  - bsgenome_name:
      type: val
      description: Name of an existing BSgenome package to use.
  - txdb:
      type: file
      description: |
        A TxDb object in SQLite format
output:
  rds:
    - "intermediate_cagerobj/normalized_clustered_cagexp.rds":
        type: file
        description: |
          Path to a CAGEr object file containing normalized CAGE data.
  results:
    - "plots/*.pdf":
        type: file
        description: |
          List of PDF files containing plots generated during normalization and clustering.
    - "plots/*.plot.rds":
        type: file
        description: |
          List of RDS files containing plots generated during normalization and clustering.
    - "plots/*.txt":
        type: file
        description: |
          List of txt files generated during normalization and clustering.
  tracks:
    - "tracks/*.bw":
        type: file
        description: |
          Raw and normalized CAGE signal tracks in bigWig format.
    - "tracks/*.bed":
        type: file
        description: |
          BED12 text tracks of per-sample tag cluster (with dominant TSS and
          interquantile block structure) and consensus cluster (single-block)
          locations.
    - "tables/*.csv":
        type: file
        description: |
          Consensus cluster expression per sample in CSV format.
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@ferenckata"
maintainers:
  - "@ferenckata"
