# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "cager_tagcluster_qc"
description: Annotate tag clusters with ChIPseeker and perform QC on nucleotide composition and consensus clusters.
keywords:
  - CAGE
  - annotation
  - QC
tools:
  - "rlang":
      description: "Functions for Base Types and Core R and 'Tidyverse' Features"
      homepage: "https://cran.r-project.org/web/packages/rlang/index.html"
      documentation: "https://rlang.r-lib.org/"
      doi: "10.32614/CRAN.package.rlang"
      licence: ["MIT + file"]
      identifier: rlang
  - "CAGEr":
      description: "Analysis of CAGE (Cap Analysis of Gene Expression) sequencing data for precise mapping of transcription start sites and promoterome mining"
      homepage: "https://www.bioconductor.org/packages/release/bioc/html/CAGEr.html"
      documentation: "https://www.bioconductor.org/packages/release/bioc/vignettes/CAGEr/inst/doc/CAGEexp.html"
      tool_dev_url: "https://github.com/charles-plessy/CAGEr"
      doi: "10.18129/B9.bioc.CAGEr"
      licence: ["GPL-3"]
      identifier: cager
  - "GenomicFeatures":
      description: "Query the gene models of a given organism/assembly"
      homepage: "https://bioconductor.org/packages/devel/bioc/html/GenomicFeatures.html"
      documentation: "https://bioconductor.org/packages/devel/bioc/vignettes/GenomicFeatures/inst/doc/GenomicFeatures.html"
      tool_dev_url: "https://github.com/Bioconductor/GenomicFeatures"
      doi: "10.1371/journal.pcbi.1003118"
      licence: ["Artistic-2.0"]
      identifier: genomicfeatures
  - "ChIPseeker":
      description: "ChIPseeker for ChIP peak Annotation, Comparison, and Visualization"
      homepage: "https://bioconductor.org/packages/release/bioc/html/ChIPseeker.html"
      documentation: "https://bioconductor.org/packages/release/bioc/vignettes/ChIPseeker/inst/doc/ChIPseeker.html"
      tool_dev_url: "https://github.com/YuLab-SMU/ChIPseeker"
      doi: "10.18129/B9.bioc.ChIPseeker"
      licence: ["Artistic-2.0"]
      identifier: chipseeker
  - "Biostrings":
      description: "Efficient manipulation of biological strings"
      homepage: "https://bioconductor.org/packages/release/bioc/html/Biostrings.html"
      documentation: "https://bioconductor.org/packages/release/bioc/manuals/Biostrings/man/Biostrings.pdf"
      tool_dev_url: "https://github.com/Bioconductor/Biostrings"
      doi: "10.18129/B9.bioc.Biostrings"
      licence: ["Artistic-2.0"]
      identifier: biostrings
  - "tidyr":
      description: "Tidy Messy Data"
      homepage: "https://cran.r-project.org/web/packages/tidyr/index.html"
      documentation: "https://tidyr.tidyverse.org/"
      tool_dev_url: "https://github.com/tidyverse/tidyr/"
      doi: "10.32614/CRAN.package.tidyr"
      licence: ["MIT + file"]
      identifier: tidyr
  - "viridis":
      description: "TColorblind-Friendly Color Maps for R"
      homepage: "https://cran.r-project.org/web/packages/viridis/index.html"
      documentation: "https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html"
      tool_dev_url: "https://github.com/sjmgarnier/viridis"
      licence: ["MIT + file"]
      doi: "10.32614/CRAN.package.viridis"
      identifier: viridis
  - "tidyverse":
      description: "Easily Install and Load the 'Tidyverse'"
      homepage: "https://cran.r-project.org/web/packages/tidyverse/index.html"
      documentation: "https://www.tidyverse.org/"
      tool_dev_url: "https://github.com/tidyverse/tidyverse"
      licence: ["MIT + file"]
      doi: "10.32614/CRAN.package.tidyverse"
      identifier: tidyverse
  - "ggplot2":
      description: "Create Elegant Data Visualisations Using the Grammar of Graphics"
      homepage: "https://cran.r-project.org/web/packages/ggplot2/index.html"
      documentation: "https://ggplot2.tidyverse.org/"
      tool_dev_url: "https://github.com/tidyverse/ggplot2/"
      doi: "10.32614/CRAN.package.gplots"
      licence: ["MIT + file"]
      identifier: ggplot2
  - "dplyr":
      description: "A grammar of data manipulation"
      homepage: "https://cloud.r-project.org/web/packages/dplyr/index.html"
      documentation: "https://dplyr.tidyverse.org/"
      tool_dev_url: "https://github.com/tidyverse/dplyr/"
      doi: "10.32614/CRAN.package.dplyr"
      licence: ["MIT + file"]
      identifier: dplyr
input:
  - cager_obj:
      type: file
      description: |
        Path to a CAGEr object file containing normalized, clustered CAGE data.
        The CAGEr object should be saved in RDS format.
      pattern: "*{.rds}"
  - txdb:
      type: file
      description: |
        A TxDb object in SQLite format
  - bsgenome_file:
      type: file
      description: The forged BSgenome package in tar.gz format.
      pattern: "BSgenome.*.tar.gz"
  - bsgenome_name:
      type: val
      description: Name of an existing BSgenome package to use.
output:
  counts_csv:
    - "tables/*.csv":
        type: file
        description: |
          File containing the tpm counts of consensus clusters per sample in CSV format.
  plots:
    - "plots/*.pdf":
        type: file
        description: |
          Path to a directory containing various plots generated during the QC process.
    - "plots/*.plot.rds":
        type: file
        description: |
          Path to a directory containing R objects of the plots generated during QC process.
  correlation_rds:
    - "plots/*correlations_matrix.rds":
        type: file
        description: |
          Path to a R object containing normaized sample correlation matrix.
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@ferenckata"
maintainers:
  - "@ferenckata"
